name: Miguel de Moura
paginate: 5
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  compress:
    css: true
    js: true
  img:
    optim: {}
  features:
    automatic_img_size: false
collections:
  posts_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: posts_tags
    values:
      layout: articles_by_tag
include:
  - _headers
exclude:
  - bin/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - package.json
  - README.md
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: posts/page/:num/
permalink: posts/:slug/
