name: Miguel de Moura
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
collections:
  pages:
    output: true
    permalink: /:path
  posts_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: posts_tags
    values:
      layout: articles_by_tag
include:
  - _headers
exclude:
  - bin/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-SA-4.0.md
  - LICENSE-MIT.md
  - package.json
  - README.md
  - yarn.lock
paginate: 5
permalink: posts/:slug/

webrick:
  headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Content-Security-Policy: "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'none'; block-all-mixed-content; base-uri 'self'; require-sri-for script style"
    Referrer-Policy: "no-referrer"
    Expect-CT: "enforce"
