name: Miguel de Moura
paginate: 5
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  features:
    automatic_img_size: true
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
collections:
  posts_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: posts_tags
    values:
      layout: articles_by_tag
include:
  - _headers
exclude:
  - bin/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - LICENSE.md
  - README.md
  - yarn.lock
  - staticman.yml
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: posts/page/:num/
permalink: posts/:slug/
