name: Miguel de Moura
url: https://migueldemoura.com
social:
  twitter: miguel_demoura
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  gzip: true
  compression: true
  defaults:
    js: { integrity: true }
    css: { integrity: false }
collections:
  pages:
    output: true
    permalink: /:path
  posts_tags:
    output: false
    permalink: /tag/:slug
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-SA-4.0.md
  - LICENSE-MIT.md
  - node_modules/
  - ruby_gems/
  - package-lock.json
  - package.json
  - README.md
permalink: posts/:slug

webrick:
  headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self' 'sha256-W8bJE+kUIdtg4j8sSoSZx6tW1A4lxbU9Lk2ApHWmX3U=' 'sha256-tQwb4c9MYnWF+1nAwjiHHEROlJRkfqlhUvmU20F/PHM='; img-src 'self'; media-src 'self'; frame-src 'none'; manifest-src 'none'; object-src 'none'; worker-src 'none'; frame-ancestors 'none'; form-action 'none'; block-all-mixed-content; base-uri 'self'"
    Cross-Origin-Resource-Policy: "same-site"
    Permissions-Policy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), encrypted-media=(), geolocation=(), fullscreen=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=()"
    Referrer-Policy: "no-referrer"
