name: Miguel de Moura
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  gzip: true
  compression: true
  defaults:
    js: {integrity: true}
    css: {integrity: false}
collections:
  pages:
    output: true
    permalink: /:path
  posts_tags:
    output: true
    permalink: /tag/:slug/
include:
  - _headers
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-SA-4.0.md
  - LICENSE-MIT.md
  - Makefile
  - node_modules/
  - ruby_gems/
  - package-lock.json
  - package.json
  - README.md
permalink: posts/:slug/

webrick:
  headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self' 'sha256-sfV11cSJxnoFkq783pLf95z7GdXBjfU7Q5gwUL7SlzY=' 'sha256-voXja0NHK+kj/CO6kVFGewEz+qyDFbxR+WW6e9vfN3o='; img-src 'self' d33wubrfki0l68.cloudfront.net; frame-src 'none'; manifest-src 'none'; object-src 'none'; worker-src 'none'; frame-ancestors 'none'; form-action 'none'; block-all-mixed-content; require-sri-for script style; base-uri 'self'"
    Referrer-Policy: "no-referrer"
    Expect-CT: "enforce"
