name: Miguel de Moura
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  compress:
    css: true
    js: true
  img:
    optim:
        default:
          verbose: true
        zero_png:
        advpng:
        gifsicle:
        jpegoptim:
        optipng:
          level: 7
        pngout:
          strategy: 0
        svgo:
  features:
    automatic_img_size: false
collections:
  pages:
    output: true
    permalink: /:path
  posts_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: posts_tags
    values:
      layout: articles_by_tag
include:
  - _headers
exclude:
  - bin/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - package.json
  - README.md
  - yarn.lock
pagination:
  enabled: true
  per_page: 5
  permalink: posts/page/:num/
  limit: 0
  sort_field: 'date'
  sort_reverse: true
permalink: posts/:slug/
