name: Miguel de Moura
url: https://migueldemoura.com
social:
  github: migueldemoura
  linkedin: migueldemoura
  email:

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - node_modules
  gzip: true
  compression: true
  defaults:
    js: {integrity: true}
    css: {integrity: false}
collections:
  pages:
    output: true
    permalink: /:path
  posts_tags:
    output: false
    permalink: /tag/:slug/
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-SA-4.0.md
  - LICENSE-MIT.md
  - node_modules/
  - ruby_gems/
  - package-lock.json
  - package.json
  - README.md
permalink: posts/:slug

webrick:
  headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self' 'sha256-O5voc83EKg87ISnJlEgeXADyj2y9vFveGolCDIKRY+A=' 'sha256-9eNozulJZxyDtPu6aYoSNZbifcLFJQt6JoN4+Zvszls='; img-src 'self'; media-src 'self'; frame-src 'none'; manifest-src 'none'; object-src 'none'; worker-src 'none'; frame-ancestors 'none'; form-action 'none'; block-all-mixed-content; require-sri-for script style; base-uri 'self'"
    Feature-Policy: "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; usb 'none'; vr 'none'"
    Referrer-Policy: "no-referrer"
