base_url = "https://migueldemoura.com"
title = "Miguel de Moura"

compile_sass = true

build_search_index = false
generate_feeds = true

feed_filenames = ["feed.xml"]

[markdown]
external_links_target_blank = true
external_links_no_referrer = true
highlight_code = true
highlight_theme = "blog"
extra_syntaxes_and_themes = ["highlight_themes"]

[extra]
twitter = "miguel_demoura"
github = "migueldemoura"
linkedin = "migueldemoura"
email = ""
