source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'jekyll-assets', :git => 'https://github.com/jekyll/jekyll-assets.git'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll'
gem 'jemoji'
gem 'mini_magick'
gem 'image_optim'
gem 'sass'
gem 'uglifier'
