name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: enable-corepack
        run: corepack enable
      - name: setup-zola
        run: |
          curl -s -L https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: sudo apt-get install -y shellcheck

      - run: |
          yarn install
      - run: |
          yarn run lint
          yarn run build
