name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: setup-zola
        run: |
          curl -s -L https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - run: sudo apt-get install -y shellcheck

      - run: |
          yarn run setup
      - run: |
          yarn run lint
          yarn run build
