name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm run setup
      - run: |
          npm run lint:sh
          npm run lint:scss
          npm run lint:js
          npm run lint:md
          npm run build
          npm run lint:html
